apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        # Forces a pod restart every time you run `helm upgrade`
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: chat-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.targetPort }}
          
          # Injecting the Environment Variables for the Go App
          env:
            - name: LOGGING_LEVEL
              value: {{ .Values.env.LOGGING_LEVEL | quote }}
            - name: CROSS_ENCODER_URL
              value: {{ .Values.env.CROSS_ENCODER_URL | quote }}
            
# Database mapping
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              value: {{ .Values.db.user | quote }}
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: frasier-db-password
                  key: password

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 10