apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        # Forces a pod restart every time you run `helm upgrade`
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: frasier-chat-ksa
      # --- THE SPOT INSTANCE HA CHEAT CODE ---
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      # ---------------------------------------
      containers:
        - name: chat-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.targetPort }}
          
          # --- RIGHT-SIZING FOR THE CHEAP POOL ---
          resources:
            requests:
              cpu: "500m"   # <-- 0.5 vCPU
              memory: "2Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          # ---------------------------------------

          # Injecting the Environment Variables for the Go App
          env:
            - name: LOGGING_LEVEL
              value: {{ .Values.env.LOGGING_LEVEL | quote }}
            - name: CROSS_ENCODER_URL
              value: {{ .Values.env.CROSS_ENCODER_URL | quote }}
            - name: RAG_RERANKER_BACKEND
              value: {{ .Values.env.RAG_RERANKER_BACKEND | quote }}
            # gemini
            # Database mapping
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              value: {{ .Values.db.user | quote }}
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: frasier-db-password
                  key: password
            - name: GEMINI_PROJECT
              value: {{ .Values.gemini.project | quote }}
            - name: GEMINI_LOCATION
              value: {{ .Values.gemini.location | quote }}
            - name: GEMINI_MODEL
              value: {{ .Values.gemini.model | quote }}            

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 10