apiVersion: v1
kind: ServiceAccount
metadata:
  name: frasier-chat-ksa
  labels:
    app: {{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: "frasier-bot-sa@pisces-12.iam.gserviceaccount.com"